"use client";

import {
  createContext,
  useContext,
  useEffect,
  useState,
  type ReactNode,
} from "react";

export type Theme = "dark" | "light";

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "sv", label: "Svenska" },
  { code: "es", label: "Español" },
  { code: "fr", label: "Français" },
  { code: "de", label: "Deutsch" },
  { code: "it", label: "Italiano" },
  { code: "pt", label: "Português" },
  { code: "ja", label: "日本語" },
  { code: "zh", label: "中文" },
  { code: "ar", label: "العربية" },
] as const;

export type LanguageCode = (typeof LANGUAGES)[number]["code"];

type Dict = Record<string, string>;

const TRANSLATIONS: Record<LanguageCode, Dict> = {
  en: {
    shop: "Shop",
    lookbook: "Lookbook",
    about: "About",
    cart: "Cart",
    shopTheDrop: "Shop the drop",
    seeLookbook: "See the Lookbook →",
    addToCart: "Add to cart",
    yourBag: "Your bag",
    empty: "Empty.",
    emptyHint: "Nothing selected yet. The drop won't wait.",
    checkout: "Checkout →",
    close: "Close",
    remove: "Remove",
    subtotal: "Subtotal",
    demoNoCheckout: "Demo — no real checkout",
    urbanUniform: "Urban Uniform",
    heroKicker: "Chapter 01 — Urban Uniform",
    subPart1: "Streetwear, engineered.",
    subPart2: "Built for the street,",
    subPart3: "cut for the body, tested in the rain.",
    scrollToEnter: "Scroll to enter",
    newCollection: "New collection",
    newDrop: "New drop",
    notifyMe: "Notify me",
    seeAll: "See all →",
    coreDrop: "Core drop.",
    featured: "/ Featured",
    chapter: "Chapter",
    manifesto: "/ Manifesto",
    manifestoText:
      "We build the uniform for people who move through the city on their own frequency. Heavyweight fabric, considered hardware, silent logos. No trend cycle — just garments that survive the commute, the club, the weather, and you.",
    lookbookLabel: "/ Lookbook — scroll",
    lookbookLabelStory: "/ Lookbook",
    nextDrop: "/ Next drop",
    dropBody:
      "Twelve pieces. Two hundred of each. Weatherproofed outerwear, deadstock indigo, technical knits. Set your alarm.",
    days: "Days",
    hours: "Hours",
    mins: "Mins",
    secs: "Secs",
    studio: "/ Studio",
    aboutTitle: "We make clothes for people who move.",
    aboutP1:
      "MARES is a small studio between Stockholm and Berlin. We design technical streetwear in limited runs — twelve pieces per season, two hundred of each, no restocks.",
    aboutP2:
      "Every garment gets a winter, a summer, a rainy autumn, and at least one 3AM club test before we approve the sample. If it fails any of them, it doesn't leave the atelier.",
    aboutP3:
      "We don't chase trends. We build an urban uniform — the layers you reach for without thinking, the ones that outlast the version of yourself that bought them.",
    valueFunctionTitle: "Function first",
    valueFunctionBody:
      "Every seam, every pocket, every zip — tested on a 40-minute commute in the rain.",
    valueNoLogoTitle: "No logo noise",
    valueNoLogoBody:
      "Debossed hardware. No chest prints. If you know, you know.",
    valueBuiltTitle: "Built to last",
    valueBuiltBody:
      "250–500gsm fabrics. Reinforced stress points. Pieces you'll retire, not replace.",
    valueRunsTitle: "Small runs",
    valueRunsBody:
      "200 of each. When it's gone, it's gone — and we move on to the next one.",
    catAll: "All",
    catOuterwear: "Outerwear",
    catTops: "Tops",
    catBottoms: "Bottoms",
    catFootwear: "Footwear",
    catAccessories: "Accessories",
    shopTitle: "Shop",
    shopIntro:
      "Twelve pieces, engineered. Filter by category — the grid reflows.",
    collection: "/ Collection",
    items: "items",
    item: "item",
    storyTitleOne: "FOUR",
    storyTitleTwo: "CHAPTERS.",
    storyChapter1H: "Concrete",
    storyChapter1B:
      "Pre-dawn on the docks. The uniform hasn't earned its name yet.",
    storyChapter2H: "Signal",
    storyChapter2B:
      "Reflective tape catches a passing tram. The city is listening.",
    storyChapter3H: "Static",
    storyChapter3B: "Cotton, fleece, silence. The in-between hours.",
    storyChapter4H: "Drift",
    storyChapter4B: "Rain on nylon. Walking home the long way on purpose.",
    lbHomeTitle1: "Concrete",
    lbHomeBody1:
      "Built for the freight elevator, the loading dock, the quiet minute before the night begins.",
    lbHomeTitle2: "Signal",
    lbHomeBody2:
      "Reflective tape, silent hardware, soft interior. Designed to disappear and reappear.",
    lbHomeTitle3: "Static",
    lbHomeBody3:
      "Heavyweight jersey, boxed shoulders, no logo. The uniform before it becomes a uniform.",
    lbHomeTitle4: "Drift",
    lbHomeBody4:
      "Wide, soft, weatherproof. For the walk home at 3AM when the city finally belongs to you.",
    footerTag: "Built for the street.",
    footerStudio: "Studio",
    footerNewsletter: "Get the drop schedule.",
    // ProductDetail
    backToShop: "Back to shop",
    color: "Color",
    size: "Size",
    securePiece: "Secure the piece →",
    shipping: "Shipping",
    returnsLabel: "Returns",
    freeOver: "Free over €250",
    returnsDays: "30 days, on us",
    // Footer
    footerShopLabel: "Shop",
    footerStockists: "Stockists",
    footerPress: "Press",
    footerContact: "Contact",
    footerSubscribe: "Subscribe",
    emailPlaceholder: "your@email",
    dropAlerts: "Drop alerts, no noise.",
    copyright: "MARES Studio. Built for the street.",
    // CartSheet
    cartLabel: "/ Cart",
    closeMark: "Close ×",
    // Loading / 404
    loading: "Loading",
    pageLost: "Lost.",
    pageLostBody: "This page isn't on the rack. Head back to the shop.",
    home: "Home →",
  },
  sv: {
    shop: "Butik",
    lookbook: "Lookbook",
    about: "Om oss",
    cart: "Kundvagn",
    shopTheDrop: "Handla släppet",
    seeLookbook: "Se Lookbooken →",
    addToCart: "Lägg i kundvagn",
    yourBag: "Din väska",
    empty: "Tom.",
    emptyHint: "Inget valt än. Släppet väntar inte.",
    checkout: "Till kassan →",
    close: "Stäng",
    remove: "Ta bort",
    subtotal: "Summa",
    demoNoCheckout: "Demo — ingen riktig kassa",
    urbanUniform: "Urban uniform",
    heroKicker: "Kapitel 01 — Urban uniform",
    subPart1: "Streetwear, konstruerat.",
    subPart2: "Byggt för gatan,",
    subPart3: "skuret för kroppen, testat i regnet.",
    scrollToEnter: "Skrolla för att gå in",
    newCollection: "Ny kollektion",
    newDrop: "Nytt släpp",
    notifyMe: "Meddela mig",
    seeAll: "Se alla →",
    coreDrop: "Kärnkollektion.",
    featured: "/ Utvalt",
    chapter: "Kapitel",
    manifesto: "/ Manifest",
    manifestoText:
      "Vi bygger uniformen för dem som rör sig genom staden på sin egen frekvens. Kraftigt tyg, genomtänkta detaljer, tysta logotyper. Ingen trendcykel — bara plagg som överlever pendlingen, klubben, vädret och dig.",
    lookbookLabel: "/ Lookbook — skrolla",
    lookbookLabelStory: "/ Lookbook",
    nextDrop: "/ Nästa släpp",
    dropBody:
      "Tolv plagg. Två hundra av varje. Väderskyddade ytterplagg, deadstock indigo, tekniska stickar. Ställ väckarklockan.",
    days: "Dagar",
    hours: "Timmar",
    mins: "Min",
    secs: "Sek",
    studio: "/ Studio",
    aboutTitle: "Vi gör kläder för människor som rör sig.",
    aboutP1:
      "MARES är en liten studio mellan Stockholm och Berlin. Vi designar teknisk streetwear i begränsade upplagor — tolv plagg per säsong, två hundra av varje, inga påfyllningar.",
    aboutP2:
      "Varje plagg får en vinter, en sommar, en regnig höst och minst ett klubbtest klockan 3 på natten innan vi godkänner provet. Om det faller på något av dem lämnar det inte ateljén.",
    aboutP3:
      "Vi jagar inte trender. Vi bygger en urban uniform — lagren du når efter utan att tänka, de som överlever den version av dig själv som köpte dem.",
    valueFunctionTitle: "Funktion först",
    valueFunctionBody:
      "Varje söm, varje ficka, varje dragkedja — testad på en 40-minuters pendling i regnet.",
    valueNoLogoTitle: "Inga logotyper",
    valueNoLogoBody: "Präglad hårdvara. Inga brösttryck. Den som vet, vet.",
    valueBuiltTitle: "Byggt att hålla",
    valueBuiltBody:
      "250–500gsm tyger. Förstärkta belastningspunkter. Plagg du pensionerar, inte byter ut.",
    valueRunsTitle: "Små upplagor",
    valueRunsBody:
      "200 av varje. När det är slut är det slut — och vi går vidare till nästa.",
    catAll: "Alla",
    catOuterwear: "Ytterplagg",
    catTops: "Överdelar",
    catBottoms: "Underdelar",
    catFootwear: "Skor",
    catAccessories: "Accessoarer",
    shopTitle: "Butik",
    shopIntro:
      "Tolv plagg, konstruerade. Filtrera efter kategori — rutnätet flödar om.",
    collection: "/ Kollektion",
    items: "plagg",
    item: "plagg",
    storyTitleOne: "KAPITEL",
    storyTitleTwo: "FYRA.",
    storyChapter1H: "Betong",
    storyChapter1B:
      "Före gryningen på hamnen. Uniformen har inte förtjänat sitt namn än.",
    storyChapter2H: "Signal",
    storyChapter2B:
      "Reflexband fångar en förbipasserande spårvagn. Staden lyssnar.",
    storyChapter3H: "Statisk",
    storyChapter3B: "Bomull, fleece, tystnad. Timmarna däremellan.",
    storyChapter4H: "Drift",
    storyChapter4B: "Regn på nylon. Den långa vägen hem med flit.",
    lbHomeTitle1: "Betong",
    lbHomeBody1:
      "Byggd för godshissen, lastkajen, den tysta minuten innan natten börjar.",
    lbHomeTitle2: "Signal",
    lbHomeBody2:
      "Reflexband, tyst hårdvara, mjukt foder. Designad att försvinna och dyka upp igen.",
    lbHomeTitle3: "Statisk",
    lbHomeBody3:
      "Kraftig jersey, boxiga axlar, ingen logotyp. Uniformen innan den blir en uniform.",
    lbHomeTitle4: "Drift",
    lbHomeBody4:
      "Vid, mjuk, vattentät. För vandringen hem klockan 3 när staden äntligen tillhör dig.",
    footerTag: "Byggt för gatan.",
    footerStudio: "Studio",
    footerNewsletter: "Få släppschemat.",
    // ProductDetail
    backToShop: "Tillbaka till butiken",
    color: "Färg",
    size: "Storlek",
    securePiece: "Säkra plagget →",
    shipping: "Frakt",
    returnsLabel: "Returer",
    freeOver: "Fri frakt över 250 €",
    returnsDays: "30 dagar, på oss",
    // Footer
    footerShopLabel: "Butik",
    footerStockists: "Återförsäljare",
    footerPress: "Press",
    footerContact: "Kontakt",
    footerSubscribe: "Prenumerera",
    emailPlaceholder: "din@mail",
    dropAlerts: "Släppnotiser, inget mer.",
    copyright: "MARES Studio. Byggt för gatan.",
    // CartSheet
    cartLabel: "/ Kundvagn",
    closeMark: "Stäng ×",
    // Loading / 404
    loading: "Laddar",
    pageLost: "Borta.",
    pageLostBody: "Den här sidan finns inte i hyllan. Tillbaka till butiken.",
    home: "Hem →",
  },
  es: {
    shop: "Tienda",
    lookbook: "Lookbook",
    about: "Nosotros",
    cart: "Carrito",
    shopTheDrop: "Comprar la colección",
    seeLookbook: "Ver el Lookbook →",
    addToCart: "Añadir al carrito",
    yourBag: "Tu bolsa",
    empty: "Vacío.",
    checkout: "Finalizar compra →",
    close: "Cerrar",
    remove: "Eliminar",
    subtotal: "Subtotal",
    urbanUniform: "Uniforme urbano",
    heroKicker: "Capítulo 01 — Uniforme urbano",
    subPart1: "Streetwear, diseñado.",
    subPart2: "Hecho para la calle,",
    subPart3: "cortado para el cuerpo, probado bajo la lluvia.",
    scrollToEnter: "Desplázate para entrar",
    newCollection: "Nueva colección",
    newDrop: "Nuevo lanzamiento",
    notifyMe: "Avísame",
    seeAll: "Ver todo →",
    coreDrop: "Colección esencial.",
    featured: "/ Destacados",
    chapter: "Capítulo",
    catAll: "Todo",
    catOuterwear: "Abrigos",
    catTops: "Camisetas",
    catBottoms: "Pantalones",
    catFootwear: "Calzado",
    catAccessories: "Accesorios",
  },
  fr: {
    shop: "Boutique",
    lookbook: "Lookbook",
    about: "À propos",
    cart: "Panier",
    shopTheDrop: "Acheter la collection",
    seeLookbook: "Voir le Lookbook →",
    addToCart: "Ajouter au panier",
    yourBag: "Votre sac",
    empty: "Vide.",
    checkout: "Commander →",
    close: "Fermer",
    remove: "Retirer",
    subtotal: "Sous-total",
    urbanUniform: "Uniforme urbain",
    heroKicker: "Chapitre 01 — Uniforme urbain",
    subPart1: "Streetwear, conçu.",
    subPart2: "Fait pour la rue,",
    subPart3: "coupé pour le corps, testé sous la pluie.",
    scrollToEnter: "Faites défiler pour entrer",
    newCollection: "Nouvelle collection",
    newDrop: "Nouvelle sortie",
    notifyMe: "Prévenez-moi",
    seeAll: "Voir tout →",
    coreDrop: "Collection essentielle.",
    featured: "/ En vedette",
    chapter: "Chapitre",
    catAll: "Tout",
    catOuterwear: "Manteaux",
    catTops: "Hauts",
    catBottoms: "Bas",
    catFootwear: "Chaussures",
    catAccessories: "Accessoires",
  },
  de: {
    shop: "Shop",
    lookbook: "Lookbook",
    about: "Über uns",
    cart: "Warenkorb",
    shopTheDrop: "Kollektion kaufen",
    seeLookbook: "Lookbook ansehen →",
    addToCart: "In den Warenkorb",
    yourBag: "Deine Tasche",
    empty: "Leer.",
    checkout: "Zur Kasse →",
    close: "Schließen",
    remove: "Entfernen",
    subtotal: "Zwischensumme",
    urbanUniform: "Urbane Uniform",
    heroKicker: "Kapitel 01 — Urbane Uniform",
    subPart1: "Streetwear, konstruiert.",
    subPart2: "Für die Straße gemacht,",
    subPart3: "für den Körper geschnitten, im Regen getestet.",
    scrollToEnter: "Scrolle zum Eintreten",
    newCollection: "Neue Kollektion",
    newDrop: "Neuer Drop",
    notifyMe: "Benachrichtigen",
    seeAll: "Alle ansehen →",
    coreDrop: "Kern-Kollektion.",
    featured: "/ Ausgewählt",
    chapter: "Kapitel",
    catAll: "Alle",
    catOuterwear: "Oberbekleidung",
    catTops: "Oberteile",
    catBottoms: "Hosen",
    catFootwear: "Schuhe",
    catAccessories: "Accessoires",
  },
  it: {
    shop: "Shop",
    lookbook: "Lookbook",
    about: "Chi siamo",
    cart: "Carrello",
    shopTheDrop: "Compra la collezione",
    seeLookbook: "Vedi il Lookbook →",
    addToCart: "Aggiungi al carrello",
    yourBag: "La tua borsa",
    empty: "Vuota.",
    checkout: "Checkout →",
    close: "Chiudi",
    remove: "Rimuovi",
    subtotal: "Subtotale",
    urbanUniform: "Uniforme urbana",
    heroKicker: "Capitolo 01 — Uniforme urbana",
    subPart1: "Streetwear, ingegnerizzato.",
    subPart2: "Fatto per la strada,",
    subPart3: "tagliato per il corpo, testato sotto la pioggia.",
    scrollToEnter: "Scorri per entrare",
    newCollection: "Nuova collezione",
    newDrop: "Nuovo drop",
    notifyMe: "Avvisami",
    seeAll: "Vedi tutto →",
    coreDrop: "Collezione essenziale.",
    featured: "/ In evidenza",
    chapter: "Capitolo",
    catAll: "Tutto",
    catOuterwear: "Capispalla",
    catTops: "Magliette",
    catBottoms: "Pantaloni",
    catFootwear: "Calzature",
    catAccessories: "Accessori",
  },
  pt: {
    shop: "Loja",
    lookbook: "Lookbook",
    about: "Sobre",
    cart: "Carrinho",
    shopTheDrop: "Comprar a coleção",
    seeLookbook: "Ver o Lookbook →",
    addToCart: "Adicionar ao carrinho",
    yourBag: "A sua mala",
    empty: "Vazio.",
    checkout: "Finalizar →",
    close: "Fechar",
    remove: "Remover",
    subtotal: "Subtotal",
    urbanUniform: "Uniforme urbano",
    heroKicker: "Capítulo 01 — Uniforme urbano",
    subPart1: "Streetwear, projetado.",
    subPart2: "Feito para a rua,",
    subPart3: "cortado para o corpo, testado na chuva.",
    scrollToEnter: "Role para entrar",
    newCollection: "Nova coleção",
    newDrop: "Novo lançamento",
    notifyMe: "Avise-me",
    seeAll: "Ver tudo →",
    coreDrop: "Coleção essencial.",
    featured: "/ Destaques",
    chapter: "Capítulo",
    catAll: "Tudo",
    catOuterwear: "Casacos",
    catTops: "Tops",
    catBottoms: "Calças",
    catFootwear: "Calçado",
    catAccessories: "Acessórios",
  },
  ja: {
    shop: "ショップ",
    lookbook: "ルックブック",
    about: "アバウト",
    cart: "カート",
    shopTheDrop: "ドロップを見る",
    seeLookbook: "ルックブックへ →",
    addToCart: "カートに追加",
    yourBag: "バッグ",
    empty: "空です。",
    checkout: "チェックアウト →",
    close: "閉じる",
    remove: "削除",
    subtotal: "小計",
    urbanUniform: "アーバンユニフォーム",
    heroKicker: "チャプター 01 — アーバンユニフォーム",
    subPart1: "設計されたストリートウェア。",
    subPart2: "街のために作られた、",
    subPart3: "身体に合わせて裁断し、雨の中でテスト済み。",
    scrollToEnter: "スクロールして入る",
    newCollection: "新コレクション",
    newDrop: "新ドロップ",
    notifyMe: "通知する",
    seeAll: "すべて見る →",
    coreDrop: "コアドロップ。",
    featured: "/ 注目",
    chapter: "チャプター",
    catAll: "すべて",
    catOuterwear: "アウター",
    catTops: "トップス",
    catBottoms: "ボトムス",
    catFootwear: "フットウェア",
    catAccessories: "アクセサリー",
  },
  zh: {
    shop: "商店",
    lookbook: "造型集",
    about: "关于",
    cart: "购物车",
    shopTheDrop: "购买系列",
    seeLookbook: "查看造型集 →",
    addToCart: "加入购物车",
    yourBag: "你的包",
    empty: "空。",
    checkout: "结账 →",
    close: "关闭",
    remove: "移除",
    subtotal: "小计",
    urbanUniform: "都市制服",
    heroKicker: "章节 01 — 都市制服",
    subPart1: "街头服饰,精心打造。",
    subPart2: "为街道而生,",
    subPart3: "为身体裁剪,经雨水测试。",
    scrollToEnter: "滚动进入",
    newCollection: "新系列",
    newDrop: "新发布",
    notifyMe: "通知我",
    seeAll: "查看全部 →",
    coreDrop: "核心系列。",
    featured: "/ 精选",
    chapter: "章节",
    catAll: "全部",
    catOuterwear: "外套",
    catTops: "上衣",
    catBottoms: "下装",
    catFootwear: "鞋履",
    catAccessories: "配饰",
  },
  ar: {
    shop: "المتجر",
    lookbook: "لوك بوك",
    about: "حول",
    cart: "عربة التسوق",
    shopTheDrop: "تسوق المجموعة",
    seeLookbook: "شاهد اللوك بوك ←",
    addToCart: "أضف إلى السلة",
    yourBag: "حقيبتك",
    empty: "فارغة.",
    checkout: "الدفع ←",
    close: "إغلاق",
    remove: "إزالة",
    subtotal: "المجموع الفرعي",
    urbanUniform: "الزي الحضري",
    heroKicker: "الفصل 01 — الزي الحضري",
    subPart1: "ملابس الشارع، مصممة.",
    subPart2: "صُنع للشارع,",
    subPart3: "مقطوع للجسم، مُختبر في المطر.",
    scrollToEnter: "مرر للدخول",
    newCollection: "مجموعة جديدة",
    newDrop: "إصدار جديد",
    notifyMe: "أعلمني",
    seeAll: "عرض الكل ←",
    coreDrop: "المجموعة الأساسية.",
    featured: "/ مميز",
    chapter: "فصل",
    catAll: "الكل",
    catOuterwear: "ملابس خارجية",
    catTops: "قمصان",
    catBottoms: "بناطيل",
    catFootwear: "أحذية",
    catAccessories: "إكسسوارات",
  },
};

type PrefsCtx = {
  theme: Theme;
  setTheme: (t: Theme) => void;
  lang: LanguageCode;
  setLang: (l: LanguageCode) => void;
  t: (key: keyof (typeof TRANSLATIONS)["en"]) => string;
};

const Ctx = createContext<PrefsCtx | null>(null);

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>("dark");
  const [lang, setLangState] = useState<LanguageCode>("en");

  useEffect(() => {
    const savedTheme = (localStorage.getItem("mares-theme") as Theme) ?? "dark";
    const savedLang =
      (localStorage.getItem("mares-lang") as LanguageCode) ?? "en";
    setThemeState(savedTheme);
    setLangState(savedLang);
    document.documentElement.setAttribute("data-theme", savedTheme);
    document.documentElement.setAttribute("lang", savedLang);
  }, []);

  const setTheme = (t: Theme) => {
    setThemeState(t);
    localStorage.setItem("mares-theme", t);
    document.documentElement.setAttribute("data-theme", t);
  };

  const setLang = (l: LanguageCode) => {
    setLangState(l);
    localStorage.setItem("mares-lang", l);
    document.documentElement.setAttribute("lang", l);
  };

  const t = (key: keyof (typeof TRANSLATIONS)["en"]) =>
    TRANSLATIONS[lang][key] ?? TRANSLATIONS.en[key];

  return (
    <Ctx.Provider value={{ theme, setTheme, lang, setLang, t }}>
      {children}
    </Ctx.Provider>
  );
}

export function usePreferences() {
  const ctx = useContext(Ctx);
  if (!ctx)
    throw new Error("usePreferences must be used inside PreferencesProvider");
  return ctx;
}
